# -*- coding: utf-8 -*-
"""Posters.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16EkgmYua0dZ8CLSwrpi08VxrloAa5o-9
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
from IPython.display import Image, display
def get_images(title):
    query = title + ' poster'
    url = 'https://www.google.com/search?q=' + query + '&tbm=isch'
    content = requests.get(url).content
    soup = BeautifulSoup(content,'lxml')# error
    images = soup.findAll('img')
    return display(Image(url=images[1].get('src')))

